### ISSUE TITLE
not working on the latest ver of macOs

### ISSUE THREAD

**Issue by liubagutu** [tom-james-watson/breaktimer-app#20]

**Comment by liubagutu** [comment]
could you fix it, please...

**Comment by tom-james-watson** [comment]
Not really sure what was going on there but I was seeing the same. Bumping a few libraries seems to have fixed the issue 😕 . I've just released a new version that should fix this. Can you please confirm it now works for you?

**Comment by liubagutu** [comment]
unfortunately,  it's still not working, the message is the same. it says that the app can't be opened since Apple can't check for malware and the app should be updated.

**Comment by tom-james-watson** [comment]
Have you downloaded the latest version from https://breaktimer.app? The app was previously not signed, which would cause it to show that error. The latest version is signed, however.

Regardless, on macOS you can simply go to the `/Applications` folder, right click the app and select `Open`. This allows you to open an unsigned app.

**Comment by liubagutu** [comment]
it's working now, sorry for disturbing you
